version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: tictactoe
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  db_test:
    image: postgres:13
    restart: always
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: tictactoe
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "8000:5432"