name: Build and Test - API and Database

on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Connect to PostgreSQL
        run: node client.js

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'

      - uses: actions/checkout@v2

      - name: install pipenv
        run: pip install pipenv
      
      - name: install pipenv development dependencies
        run: pipenv sync --dev
  
      - name: run pytest
        run: pipenv run pytest -v

      - name: run flake8
        run: pipenv run flake8 .

      - name: run black
        run: pipenv run black --check .