name: Build and Test - Frontend

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - uses: actions/checkout@v2

      - name: install packages
        working-directory: ./frontend
        run: npm install --dev
      
      - name: install OpenAPI client folder
        working-directory: ./frontend
        run: npm run generate-client

      - name: run tests using react testing library
        working-directory: ./frontend
        run: npm run tests

      - name: launch frontend on port 3001
        working-directory: ./frontend
        run: npm start
      