name: Build and Test

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'

      - uses: actions/checkout@v2

      - name: install pipenv
        run: pip install pipenv
      
      - name: install pipenv
        run: pipenv install
      
      - name: install pipenv development dependencies
        run: pipenv install --dev
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run pytest
        run: pipenv run pytest -v

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run flake8
        run: pipenv run flake8

      - name: run black
        run: pipenv run black
      