name: Build and Test - Frontend

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - uses: actions/checkout@v2

      - name: install packages
        run: npm install
      
      - name: install OpenAPI client
        run: npm run generate-client

      - name: launch frontend on port 3001
        run: npm start