name: Build and Test - Frontend

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - uses: actions/checkout@v2

      - name: install packages
        run: npm install --dev

      - name: launch backend to enable client
        working-directory: ./backend
        run: uvicorn --port 3000 tic_tac_toe_api.api:app --reload
      
      - name: install OpenAPI client folder
        run: npm run generate-client

      - name: run tests using react testing library
        run: npm run tests

      - name: launch frontend on port 3001
        run: npm start
      