name: Build and Test

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'

      - uses: actions/checkout@v2

      - name: install dependencies
        run: pip install pytest

      - name: run pytest
        run: pytest -v

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Super-Linter
  #       uses: github/super-linter:slim-v4
  #       env:
  #         GITHUB_TOKEN: ${{ secrets. }}
  #         DEFAULT_BRANCH: walking-skeleton