name: Build and Test - API and Database

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SQLALCHEMY_CONN: postgresql://postgres@localhost:8000/tictactoe
      SQLALCHEMY_CONN: postgresql://postgres@localhost:8000/tictactoe

    defaults:
      run:
        working-directory: ./backend

    services:
      db_test:
        image: postgres:13
        environment:
          TZ: UTC
          PGTZ: UTC
          POSTGRES_DB: tictactoe
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        ports:
          - 8000:5432

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install pipenv
        run: pip install pipenv
      
      - name: install pipenv development dependencies
        run: pipenv sync --dev
  
      - name: run pytest
        run: pipenv run pytest -v

      - name: run flake8
        run: pipenv run flake8 .

      - name: run black
        run: pipenv run black --check .